### ISSUE TITLE
Linux development support?

### ISSUE THREAD

**Issue by imgeorgiev** [merschformann/RAWSim-O#8] opened 2021-12-15 16:19 UTC
Is this project intended to support Linux? If so would it be possible to get some build instructions?

The root readme only details how to build and launch with VS which isn't available on Linux. Building with xbuild, NET 6.0 and the default Linux build tools [mono](https://www.mono-project.com/) doesn't work I am afraid. The Turbo C# (`mcs`) compiler produces similar results. 

```
~/git/RAWSim-O   main ±   xbuild /p:Configuration=Mono /p:Platform=x64 RAWSimO.Visualization/RAWSimO.Visualization.csproj 

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 6.8.0.105
Copyright (C) 2005-2013 Various Mono authors

Build started 12/15/2021 5:15:13 PM.
__________________________________________________
Project "/home/ignat/git/RAWSim-O/RAWSimO.Visualization/RAWSimO.Visualization.csproj" (default target(s)):
	Target RestorePackages:
		Executing: mono --runtime=v4.0.30319 "../.nuget/NuGet.exe" install "/home/ignat/git/RAWSim-O/RAWSimO.Visualization/packages.config" -source ""   -RequireConsent -solutionDir "../"
		Restoring NuGet packages...
		To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
	Target PrepareForBuild:
		Configuration: Mono Platform: x64
	Target ResolveProjectReferences:
		Project "/home/ignat/git/RAWSim-O/RAWSimO.CommFramework/RAWSimO.CommFramework.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Mono Platform: x64
			Target ResolveProjectReferences:
				Project "/home/ignat/git/RAWSim-O/RAWSimO.Core/RAWSimO.Core.csproj" (default target(s)):
					Target PrepareForBuild:
						Configuration: Mono Platform: x64
					Target ResolveProjectReferences:
						Project "/home/ignat/git/RAWSim-O/RAWSimO.MultiAgentPathFinding/RAWSimO.MultiAgentPathFinding.csproj" (default target(s)):
							Target PrepareForBuild:
								Configuration: Mono Platform: x64
							Target ResolveProjectReferences:
								Project "/home/ignat/git/RAWSim-O/RAWSimO.Toolbox/RAWSimO.Toolbox.csproj" (default target(s)):
									Target PrepareForBuild:
										Configuration: Mono Platform: x64
									Target GenerateSatelliteAssemblies:
									No input files were specified for target GenerateSatelliteAssemblies, skipping.
									Target _GenerateTargetFrameworkMonikerAttribute:
									Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
									Target CoreCompile:
									Skipping target "CoreCompile" because its outputs are up-to-date.
								Done building project "/home/ignat/git/RAWSim-O/RAWSimO.Toolbox/RAWSimO.Toolbox.csproj".
							Target GenerateSatelliteAssemblies:
							No input files were specified for target GenerateSatelliteAssemblies, skipping.
							Target _GenerateTargetFrameworkMonikerAttribute:
							Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
							Target CoreCompile:
							Skipping target "CoreCompile" because its outputs are up-to-date.
						Done building project "/home/ignat/git/RAWSim-O/RAWSimO.MultiAgentPathFinding/RAWSimO.MultiAgentPathFinding.csproj".
					Target GenerateSatelliteAssemblies:
					No input files were specified for target GenerateSatelliteAssemblies, skipping.
					Target _GenerateTargetFrameworkMonikerAttribute:
					Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
					Target CoreCompile:
					Skipping target "CoreCompile" because its outputs are up-to-date.
				Done building project "/home/ignat/git/RAWSim-O/RAWSimO.Core/RAWSimO.Core.csproj".
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target _GenerateTargetFrameworkMonikerAttribute:
			Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
		Done building project "/home/ignat/git/RAWSim-O/RAWSimO.CommFramework/RAWSimO.CommFramework.csproj".
		Project "/home/ignat/git/RAWSim-O/RAWSimO.DataPreparation/RAWSimO.DataPreparation.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Mono Platform: x64
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target _GenerateTargetFrameworkMonikerAttribute:
			Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
			Skipping target "CoreCompile" because its outputs are up-to-date.
			Target _CopyAppConfigFile:
			Skipping target "_CopyAppConfigFile" because its outputs are up-to-date.
		Done building project "/home/ignat/git/RAWSim-O/RAWSimO.DataPreparation/RAWSimO.DataPreparation.csproj".
		Project "/home/ignat/git/RAWSim-O/RAWSimO.Playground/RAWSimO.Playground.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Mono Platform: x64
			Target ResolveProjectReferences:
				Project "/home/ignat/git/RAWSim-O/RAWSimO.CLI/RAWSimO.CLI.csproj" (default target(s)):
					Target PrepareForBuild:
						Configuration: Mono Platform: x64
					Target GenerateSatelliteAssemblies:
					No input files were specified for target GenerateSatelliteAssemblies, skipping.
					Target _GenerateTargetFrameworkMonikerAttribute:
					Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
					Target CoreCompile:
					Skipping target "CoreCompile" because its outputs are up-to-date.
					Target _CopyAppConfigFile:
					Skipping target "_CopyAppConfigFile" because its outputs are up-to-date.
				Done building project "/home/ignat/git/RAWSim-O/RAWSimO.CLI/RAWSimO.CLI.csproj".
				Project "/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/RAWSimO.VisualToolbox.csproj" (default target(s)):
					Target PrepareForBuild:
						Configuration: Mono Platform: x64
					Target ResolveAssemblyReferences:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'PresentationCore' not resolved
						For searchpath {CandidateAssemblyFiles}
						Warning: {CandidateAssemblyFiles} not supported currently
						For searchpath {HintPathFromItem}
						HintPath attribute not found
						For searchpath {TargetFrameworkDirectory}
						Considered target framework dir /usr/lib/mono/4.5-api/, assembly named 'PresentationCore' not found.
						Considered target framework dir /usr/lib/mono/4.5-api//Facades/, assembly named 'PresentationCore' not found.
						For searchpath {PkgConfig}
						Considered PresentationCore, but could not find in any pkg-config files.
						For searchpath {GAC}
						Considered PresentationCore, but could not find in the GAC.
						For searchpath {RawFileName}
						Considered 'PresentationCore' as a file, but the file does not exist
						For searchpath bin/x64/Mono/
						Considered '/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/bin/x64/Mono/PresentationCore' as a file, but the file does not exist
						Considered '/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/bin/x64/Mono/PresentationCore.exe' as a file, but the file does not exist
						Considered '/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/bin/x64/Mono/PresentationCore.dll' as a file, but the file does not exist
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'PresentationFramework' not resolved
						For searchpath {CandidateAssemblyFiles}
						Warning: {CandidateAssemblyFiles} not supported currently
						For searchpath {HintPathFromItem}
						HintPath attribute not found
						For searchpath {TargetFrameworkDirectory}
						Considered target framework dir /usr/lib/mono/4.5-api/, assembly named 'PresentationFramework' not found.
						Considered target framework dir /usr/lib/mono/4.5-api//Facades/, assembly named 'PresentationFramework' not found.
						For searchpath {PkgConfig}
						Considered PresentationFramework, but could not find in any pkg-config files.
						For searchpath {GAC}
						Considered PresentationFramework, but could not find in the GAC.
						For searchpath {RawFileName}
						Considered 'PresentationFramework' as a file, but the file does not exist
						For searchpath bin/x64/Mono/
						Considered '/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/bin/x64/Mono/PresentationFramework' as a file, but the file does not exist
						Considered '/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/bin/x64/Mono/PresentationFramework.exe' as a file, but the file does not exist
						Considered '/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/bin/x64/Mono/PresentationFramework.dll' as a file, but the file does not exist
					Target GenerateSatelliteAssemblies:
					No input files were specified for target GenerateSatelliteAssemblies, skipping.
					Target _GenerateTargetFrameworkMonikerAttribute:
					Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
					Target CoreCompile:
						Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug:portable /out:obj/x64/Mono/RAWSimO.VisualToolbox.dll Arrows/ArrowEnds.cs Arrows/ArrowLineGeometryGenerator.cs Properties/AssemblyInfo.cs AnimationHelper.cs ZoomAndPanControl.cs ZoomAndPanControl_IScrollInfo.cs obj/x64/Mono/.NETFramework,Version=v4.5.AssemblyAttribute.cs /target:library /define:"DEBUG;TRACE" /nostdlib /platform:x64 /reference:/usr/lib/mono/4.5-api/System.dll /reference:/usr/lib/mono/4.5-api/System.Xaml.dll /reference:/usr/lib/mono/4.5-api/System.Xml.Linq.dll /reference:/usr/lib/mono/4.5-api/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.5-api/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5-api/System.Data.dll /reference:/usr/lib/mono/4.5-api/System.Xml.dll /reference:/usr/lib/mono/4.5-api/WindowsBase.dll /reference:/usr/lib/mono/4.5-api/System.Core.dll /reference:/usr/lib/mono/4.5-api//mscorlib.dll
AnimationHelper.cs(6,28): error CS0234: The type or namespace name `Animation' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
ZoomAndPanControl.cs(5,22): error CS0234: The type or namespace name `Controls' does not exist in the namespace `System.Windows'. Are you missing an assembly reference?
ZoomAndPanControl.cs(8,28): error CS0234: The type or namespace name `Animation' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
ZoomAndPanControl.cs(11,22): error CS0234: The type or namespace name `Controls' does not exist in the namespace `System.Windows'. Are you missing an assembly reference?
ZoomAndPanControl_IScrollInfo.cs(7,22): error CS0234: The type or namespace name `Controls' does not exist in the namespace `System.Windows'. Are you missing an assembly reference?
ZoomAndPanControl.cs(20,46): error CS0246: The type or namespace name `ContentControl' could not be found. Are you missing an assembly reference?
ZoomAndPanControl.cs(20,62): error CS0246: The type or namespace name `IScrollInfo' could not be found. Are you missing an assembly reference?
Arrows/ArrowLineGeometryGenerator.cs(25,23): error CS0246: The type or namespace name `Geometry' could not be found. Are you missing an assembly reference?
Arrows/ArrowLineGeometryGenerator.cs(77,24): error CS0246: The type or namespace name `PathFigure' could not be found. Are you missing an assembly reference?
AnimationHelper.cs(20,43): error CS0246: The type or namespace name `UIElement' could not be found. Are you missing an assembly reference?
AnimationHelper.cs(29,43): error CS0246: The type or namespace name `UIElement' could not be found. Are you missing an assembly reference?
AnimationHelper.cs(61,44): error CS0246: The type or namespace name `UIElement' could not be found. Are you missing an assembly reference?
ZoomAndPanControl.cs(27,17): error CS0246: The type or namespace name `FrameworkElement' could not be found. Are you missing an assembly reference?
ZoomAndPanControl.cs(32,17): error CS0246: The type or namespace name `ScaleTransform' could not be found. Are you missing an assembly reference?
ZoomAndPanControl.cs(37,17): error CS0246: The type or namespace name `TranslateTransform' could not be found. Are you missing an assembly reference?
ZoomAndPanControl.cs(110,17): error CS0246: The type or namespace name `ScrollViewer' could not be found. Are you missing an assembly reference?
ZoomAndPanControl.cs(578,30): error CS0115: `RAWSimO.VisualToolbox.ZoomAndPanControl.OnApplyTemplate()' is marked as an override but no suitable method found to override
ZoomAndPanControl.cs(973,33): error CS0115: `RAWSimO.VisualToolbox.ZoomAndPanControl.MeasureOverride(System.Windows.Size)' is marked as an override but no suitable method found to override
ZoomAndPanControl.cs(1024,33): error CS0115: `RAWSimO.VisualToolbox.ZoomAndPanControl.ArrangeOverride(System.Windows.Size)' is marked as an override but no suitable method found to override
ZoomAndPanControl_IScrollInfo.cs(104,16): error CS0246: The type or namespace name `ScrollViewer' could not be found. Are you missing an assembly reference?
ZoomAndPanControl_IScrollInfo.cs(297,33): error CS0246: The type or namespace name `Visual' could not be found. Are you missing an assembly reference?
					Task "Csc" execution -- FAILED
					Done building target "CoreCompile" in project "/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/RAWSimO.VisualToolbox.csproj".-- FAILED
				Done building project "/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/RAWSimO.VisualToolbox.csproj".-- FAILED
			Task "MSBuild" execution -- FAILED
			Done building target "ResolveProjectReferences" in project "/home/ignat/git/RAWSim-O/RAWSimO.Playground/RAWSimO.Playground.csproj".-- FAILED
		Done building project "/home/ignat/git/RAWSim-O/RAWSimO.Playground/RAWSimO.Playground.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "ResolveProjectReferences" in project "/home/ignat/git/RAWSim-O/RAWSimO.Visualization/RAWSimO.Visualization.csproj".-- FAILED
Done building project "/home/ignat/git/RAWSim-O/RAWSimO.Visualization/RAWSimO.Visualization.csproj".-- FAILED

Build FAILED.

Warnings:

/home/ignat/git/RAWSim-O/RAWSimO.Visualization/RAWSimO.Visualization.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/home/ignat/git/RAWSim-O/RAWSimO.Playground/RAWSimO.Playground.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/RAWSimO.VisualToolbox.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'PresentationCore' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'PresentationFramework' not resolved

Errors:

/home/ignat/git/RAWSim-O/RAWSimO.Visualization/RAWSimO.Visualization.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/home/ignat/git/RAWSim-O/RAWSimO.Playground/RAWSimO.Playground.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/home/ignat/git/RAWSim-O/RAWSimO.VisualToolbox/RAWSimO.VisualToolbox.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	AnimationHelper.cs(6,28): error CS0234: The type or namespace name `Animation' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
	ZoomAndPanControl.cs(5,22): error CS0234: The type or namespace name `Controls' does not exist in the namespace `System.Windows'. Are you missing an assembly reference?
	ZoomAndPanControl.cs(8,28): error CS0234: The type or namespace name `Animation' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
	ZoomAndPanControl.cs(11,22): error CS0234: The type or namespace name `Controls' does not exist in the namespace `System.Windows'. Are you missing an assembly reference?
	ZoomAndPanControl_IScrollInfo.cs(7,22): error CS0234: The type or namespace name `Controls' does not exist in the namespace `System.Windows'. Are you missing an assembly reference?
	ZoomAndPanControl.cs(20,46): error CS0246: The type or namespace name `ContentControl' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl.cs(20,62): error CS0246: The type or namespace name `IScrollInfo' could not be found. Are you missing an assembly reference?
	Arrows/ArrowLineGeometryGenerator.cs(25,23): error CS0246: The type or namespace name `Geometry' could not be found. Are you missing an assembly reference?
	Arrows/ArrowLineGeometryGenerator.cs(77,24): error CS0246: The type or namespace name `PathFigure' could not be found. Are you missing an assembly reference?
	AnimationHelper.cs(20,43): error CS0246: The type or namespace name `UIElement' could not be found. Are you missing an assembly reference?
	AnimationHelper.cs(29,43): error CS0246: The type or namespace name `UIElement' could not be found. Are you missing an assembly reference?
	AnimationHelper.cs(61,44): error CS0246: The type or namespace name `UIElement' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl.cs(27,17): error CS0246: The type or namespace name `FrameworkElement' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl.cs(32,17): error CS0246: The type or namespace name `ScaleTransform' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl.cs(37,17): error CS0246: The type or namespace name `TranslateTransform' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl.cs(110,17): error CS0246: The type or namespace name `ScrollViewer' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl.cs(578,30): error CS0115: `RAWSimO.VisualToolbox.ZoomAndPanControl.OnApplyTemplate()' is marked as an override but no suitable method found to override
	ZoomAndPanControl.cs(973,33): error CS0115: `RAWSimO.VisualToolbox.ZoomAndPanControl.MeasureOverride(System.Windows.Size)' is marked as an override but no suitable method found to override
	ZoomAndPanControl.cs(1024,33): error CS0115: `RAWSimO.VisualToolbox.ZoomAndPanControl.ArrangeOverride(System.Windows.Size)' is marked as an override but no suitable method found to override
	ZoomAndPanControl_IScrollInfo.cs(104,16): error CS0246: The type or namespace name `ScrollViewer' could not be found. Are you missing an assembly reference?
	ZoomAndPanControl_IScrollInfo.cs(297,33): error CS0246: The type or namespace name `Visual' could not be found. Are you missing an assembly reference?

	 2 Warning(s)
	 21 Error(s)

Time Elapsed 00:00:02.0635560
```

**Comment by merschformann** [comment] 2021-12-16 13:30
Yeah. Unfortunately, it won't compile fully for Linux. :disappointed: 

The problem is mainly with the UI projects. They rely on WPF which is not supported for Linux by mono and sadly not even by more up to date versions of .Net.

I was thinking about overhauling the whole project to bring it to a recent version of .Net and maybe also replace the WPF dependency with something else. Maybe [Avalonia](https://github.com/AvaloniaUI/Avalonia) or [Uno](https://github.com/unoplatform/uno) could help. :shrug: I am not writing much C# anymore nowadays, thus, other recommendations are much appreciated. :relaxed: 

I may have some time this weekend to look into this in more depth. I would love it to support Linux desktop myself. :100: 

However, What should work though is running the headless parts (e.g. `RAWSimO.CLI`) on Linux. They should successfully build when running `xbuild /p:Configuration=Mono /p:Platform=x64 RAWSimO.sln` (UI projects should get skipped). I used them back at University with the compute cluster for conducting my experiments. Test it for example with: `mono RAWSimO.CLI\bin\x86\Mono\RAWSimO.CLI.exe Material\Instances\CoreBenchmark\jenkins1.xinst Material\Instances\CoreBenchmark\jenkins1.xsett Material\Instances\CoreBenchmark\jenkins1.xconf . 1`
Of course, this is only partially helpful, since the UI offers an a bit easier way of creating the necessary configurations (`.xlayo`, etc.). :grimacing:

**Comment by imgeorgiev** [comment] 2021-12-16 15:36
I don't need a GUI, so that's all perfect, thanks! I'll condense information as I make my way working with this on Linux and submit a PR with some help for others in my shoes :)

**Comment by merschformann** [comment] 2021-12-16 15:54
That would be great! Thank you! :hugs: 

Nevertheless, I will give switching the UI over to some other framework some thought during the weekend. I would really prefer to allow this to be `xplat`. Let's see whether there are somewhat low hanging fruits to do it. :monocle_face:

**Comment by merschformann** [comment] 2022-01-05 22:42
https://github.com/merschformann/RAWSim-O/pull/9 just converted RAWSim-O to .Net 5. It should now "natively" work on Linux (without the need for mono). I also added an "XPlat" configuration which only builds the projects supported on other platforms. I.e., all non-UI projects unfortunately. If I ever find the time I would like to convert the UIs from WPF to Avalonia in order to support other platforms. However, I hope this works sufficiently well for now.

I will close this as the main request seems to be fulfilled. :relaxed:

**Closed by merschformann** 2022-01-05 22:42 UTC

**Comment by imgeorgiev** [comment] 2022-01-06 14:47
Awesome, thanks for the extra support!
